services:
  - type: web
    name: instagram-telegram-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true